yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
]

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    """ Создание модели для таблицы Сообщества."""
    title = models.CharField(max_length=200, verbose_name='Group title')
    slug = models.SlugField(unique=True, verbose_name='Relative URL')
    description = models.TextField(
        null=True, blank=True,
        verbose_name='Group description'
    )

    def _str_(self) -> str:
        return self.title


class Post(models.Model):
    """ Создание модели для таблицы Постов."""
    text = models.TextField(
        max_length=300, verbose_name="текст поста")
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации',
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts'
    )
    author = models.ForeignKey(
        User,
        null=True,
        on_delete=models.CASCADE,
        related_name='posts'
    )

    class Meta:
        verbose_name = 'Пост'
        ordering = ['-pub_date']

    def __str__(self):
        return self.text

yatube/posts/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group')

    def clean_group(self):
        group = self.cleaned_data['group']
        return group

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import PostForm
from .models import Group, Post, User

POSTS_NUMB = 10


def group_posts(request, slug):
    """Функция group_posts передает данные в шаблон group_list.html."""
    group = get_object_or_404(Group, slug=slug)
    post_list = (group.posts.select_related("author").
                 order_by('-pub_date'))
    # Паджинация 10 постов на страницу
    paginator = Paginator(post_list, POSTS_NUMB)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def index(request):
    """Функция index передает данные в шаблон index.html."""
    # Паджинация 10 постов на страницу
    post_list = (Post.objects.select_related("author").
                 order_by('-pub_date'))
    paginator = Paginator(post_list, POSTS_NUMB)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    # Здесь код запроса к модели и создание словаря контекста
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def profile(request, username):
    """Здесь код запроса к модели и создание словаря контекста."""
    author = get_object_or_404(User, username=username)
    # В тело страницы выведен список постов
    post_list = (author.posts.select_related("author").
                 order_by('-pub_date'))
    # Выведено общее количество постов пользователя
    count = author.posts.count()
    # Паджинация 10 постов на страницу
    paginator = Paginator(post_list, POSTS_NUMB)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'author': author,
        'count': count,
        'posts': post_list,
        'page_obj': page_obj,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    """Здесь код запроса к модели и создание словаря контекста."""
    post = get_object_or_404(Post, pk=post_id)
    # В тело страницы выведен один пост, выбранный по pk
    context = {'post': post, }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    """Добавлена "Новая запись" для авторизованных пользователей."""
    if request.method == "POST":
        form = PostForm(request.POST or None)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('posts:profile', post.author.username)
        return render(request, 'posts/post_create.html', {'form': form})
    form = PostForm()
    return render(request, 'posts/post_create.html', {'form': form})


@login_required
def post_edit(request, post_id):
    """Добавлена страница редактирования записи."""
    # Права на редактирование должны быть только у автора этого поста
    # Остальные пользователи должны перенаправляться
    # На страницу просмотра поста
    post = Post.objects.get(pk=post_id)
    form = PostForm(None, instance=post)
    if request.user != post.author:
        return redirect('posts:post_detail', post_id)
    form = PostForm(request.POST or None, instance=post)
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)
    return render(
        request,
        'posts/post_create.html',
        {'form': form, 'is_edit': True, 'post_id': post_id})

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
  {% if is_edit %}
    Редактировать запись
  {% else %}
    Новый пост
  {% endif %}
{% endblock %}

{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        {% if is_edit %}
          Редактировать запись
        {% else %}
          Новый пост
        {% endif %}
      </div>
      <div class="card-body">
        {% load user_filters %}
        <form method="post" 
          {% csrf_token %}
          <div class="form-group row my-3 p-3">
            <label for="form.text.id_for_label">
              Текст поста
              <span class="required text-danger" >*</span>
            </label>
            {{ form.text|addclass:'form-control' }}
            <small id="id_text-help" class="form-text text-muted">
              Текст нового поста
            </small>
          </div>
          <div class="form-group row my-3 p-3">
            <label for="form.group.id_for_label">
              Группа
            </label>
            {{ form.group|addclass:'form-control' }}
            <small id="id_group-help" class="form-text text-muted">
              Группа, к которой будет относиться пост
            </small>
          </div>
          <div class="d-flex justify-content-end">

            <button type="submit" class="btn btn-primary">
              {% if is_edit %}
                Сохранить
              {% else %}
                Добавить
              {% endif %}
            </button>

          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %} {{ group.title }} {% endblock %}
{% block content %}
<div class="container py-5">
  <h1>{{ group.title }} </h1>
  <p> {{ group.description }} </p>
  {% for post in page_obj %}
    <article>
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
          <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      <p>{{ post.text }}</p>
      <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
    </article>
    {% if post.group %}
      <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
</div>
{% endblock %}

yatube/templates/posts/index.html
{% extends "base.html" %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block header %}Последние обновления на сайте{% endblock %}
{% block content %}

  {% for post in page_obj %}
        <article> 
        <ul> 
            <li> 
                Группа: {{ post.group.title }} 
            </li> 
            <li>     
                Автор: {{ post.author.get_full_name }}  
            </li> 
            <li> 
                Дата публикации: {{ post.pub_date|date:"d E Y" }} 
            </li>     
        </ul> 
        <p>{{post.text }}</p> 
        {% if post.group  and not group %}   
            <a href="{% url 'posts:group_list' post.group.slug  %}">все записи группы</a>           
            {% endif %} 
        {% if not forloop.last %}<hr>{% endif %} 
        </article> 
    {% endfor %} 
    {% include 'posts/includes/paginator.html' %}
{% endblock %} 

yatube/templates/posts/post_create.html
{% extends 'base.html' %}
{% block title %}
  {% if is_edit %}
    Редактировать запись
  {% else %}
    Новый пост
  {% endif %}
{% endblock %}

{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        {% if is_edit %}
          Редактировать запись
        {% else %}
          Новый пост
        {% endif %}
      </div>
      <div class="card-body">
        {% load user_filters %}
        <form method="post" 
          {% csrf_token %}
          <div class="form-group row my-3 p-3">
            <label for="form.text.id_for_label">
              Текст поста
              <span class="required text-danger" >*</span>
            </label>
            {{ form.text|addclass:'form-control' }}
            <small id="id_text-help" class="form-text text-muted">
              Текст нового поста
            </small>
          </div>
          <div class="form-group row my-3 p-3">
            <label for="form.group.id_for_label">
              Группа
            </label>
            {{ form.group|addclass:'form-control' }}
            <small id="id_group-help" class="form-text text-muted">
              Группа, к которой будет относиться пост
            </small>
          </div>
          <div class="d-flex justify-content-end">

            <button type="submit" class="btn btn-primary">
              {% if is_edit %}
                Сохранить
              {% else %}
                Добавить
              {% endif %}
            </button>

          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}
  Пост {{ post.text|truncatechars:30 }}
{% endblock %} 
{% block content %}
  <body>
    <main>
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
            {% if post.group %}
            <li class="list-group-item">
              Группа: {{ post.group }}
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:group_list' post.group.slug %}">
                все записи группы
              </a>
            </li>
              {% endif %}
            
            <li class="list-group-item">
              Автор: {{ post.author.get_full_name }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора: {{ post.author.posts.count  }}
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author %}">
                все посты пользователя
              </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          <p>
          {{ post.text|linebreaksbr }}
          </p>
          {% if post.author == request.user %}
          <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk %}">редактировать запись </a>
          {% else %}
          <a class="btn btn-outline-secondary disabled" href="#">редактировать запись </a>
          <br/><br/>
          <p>Вы не можете редактировать чужую запись </p>
          {% endif %}
        </article>
      </div> 
    </main>
  </body>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}
  Все посты пользователя{{ author }}
{% endblock %} 
{% block content %}
  <body>  
    <main>
      <div class="container py-5">        
        <h1>Все посты пользователя {{ author.get_full_name }}</h1>
        <h3>Всего постов: {{ author.posts.count }}</h3>   
    {% for post in page_obj %}
        <article>
          <ul>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
        
          <p>
            {{ post.text|linebreaksbr }}
          </p>
          <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
        
               
        {% if post.group %}   
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
      {% endif %}
      </article>       
        {% if not forloop.last %}<hr>{% endif %} 
        {% endfor %}
        {% include 'posts/includes/paginator.html' %} 
      </div>
    </main>
  </body>
{% endblock %}